services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: gush_ball
      POSTGRES_PASSWORD: gush_ball
      POSTGRES_DB: gush_ball
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
