"""add game scrape suggestion

Revision ID: 72934e3e707e
Revises: c184ab22ef39
Create Date: 2026-09-28 20:03:52.699739

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72934e3e707e'
down_revision: str | Sequence[str] | None = 'c184ab22ef39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('scrape_suggestion', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('games', sa.Column('scrape_suggestion_dismissed', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'scrape_suggestion_dismissed')
    op.drop_column('games', 'scrape_suggestion')
    # ### end Alembic commands ###
