"""add standing_rows

Revision ID: 956f6ddf6896
Revises: 6f6897600cce
Create Date: 2026-09-28 13:18:15.141838

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '956f6ddf6896'
down_revision: str | Sequence[str] | None = '6f6897600cce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standing_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=120), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Integer(), nullable=False),
    sa.Column('points_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_name', 'team_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standing_rows')
    # ### end Alembic commands ###
