"""add game scrape columns

Revision ID: c184ab22ef39
Revises: 956f6ddf6896
Create Date: 2026-09-28 15:22:29.009572

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c184ab22ef39'
down_revision: str | Sequence[str] | None = '956f6ddf6896'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('source_event_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('is_scraped', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('games', sa.Column('needs_review', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('games', sa.Column('is_manually_overridden', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_unique_constraint('uq_games_source_event_id', 'games', ['source_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_source_event_id', 'games', type_='unique')
    op.drop_column('games', 'is_manually_overridden')
    op.drop_column('games', 'needs_review')
    op.drop_column('games', 'is_scraped')
    op.drop_column('games', 'source_event_id')
    # ### end Alembic commands ###
